pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: spontoreau.rust-vsts.rust-install.Rust@1
  displayName: 'Rust Tool Installer'

- task: spontoreau.rust-vsts.rust-cargo.Cargo@1
  displayName: Cargo
  inputs:
    cargoCommand: test
